
research_sites:
        bancomundial:
                url: https://www.worldbank.org/en/research
                queries:
                        homepage_article_links : '.lp__card_content a'
                        article_body: '.redesign_static_content section p'
                        article_title: 'h1'            
        oms:
                url: https://www.who.int/es
                queries:
                        homepage_article_links : ''
                        article_body: ''
                        article_title: ''
                          
               
