
research_sites:
        bancomundial:
                url: https://www.worldbank.org/en/research
                queries:
                        homepage_article_links : '.lp__card_content a'
                        article_body: '.redesign_static_content section p'
                        article_title: 'h1'            
        oms:
                url: https://www.who.int/es
                queries:
                        homepage_article_links : ''
                        article_body: ''
                        article_title: ''
        eluniversal:
                url: http://www.eluniversal.com.mx
                queries:
                        homepage_article_links: '.field-content a'
                        article_body: '.field-name-body'
                        article_title: '.pane-content h1'  
        elpais:
                url: https://elpais.com
                queries:
                        homepage_article_links: '.article h2 a'
                        article_body: '.article p'
                        article_title: '.article h2 a'                
         
        washingtonpost:
                url: https://www.washingtonpost.com
                queries:
                        homepage_article_links: '.headline a'
                        article_body: '.topper-headline h1'
                        article_title: 'article.paywall'
       
